language: php

matrix:
  include:
    - php: 7.4
    - php: 8.0
    - php: nightly

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit

notifications:
  email:
    - crevillo@gmail.com
