language: php

matrix:
  include:
    - php: 7.4

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - bin/phpunit

notifications:
  email:
    - crevillo@gmail.com
